# Site settings
title: "AAAAAA"
description: "BBBBBBBBB"
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "wersfz"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: hnbloggithub
